### ISSUE TITLE
Domain has expired

### ISSUE THREAD

**Issue by doolio** [sanity/LastCalc#28]
Just an fyi.

**Comment by sanity** [comment]
Ah, thanks for the heads-up.  I assume you mean lastcalc.com?  I had let it expire because I thought people had only used lastcalc.com - may I ask where you found the link to it?

Anyway, I've restored it - it should work again soon.

**Comment by doolio** [comment]
Hmm, the two urls in your comment above appear the same. In any case, I noticed the domain had expired when I clicked on the link in the sidebar of your blog where you list your current and past projects. Didn't want you to lose your domain for this project. I follow your work here too so I thought it easiest to open this as an issue.

**Comment by sanity** [comment]
Thanks, I assume it's working ok now?

**Comment by doolio** [comment]
Yes, it's all working again. Thanks.
